# Generated by Django 4.1.5 on 2023-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='crewmates_num',
            field=models.IntegerField(null=True),
        ),
    ]
