# Generated by Django 4.1.5 on 2023-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks_app', '0002_tank_crewmates_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='turret',
            field=models.BooleanField(null=True),
        ),
    ]
